name: 'LaunchDarkly Gosec'
description: 'Run gosec and upload the resutls to s3 and workflow artifacts'

inputs:
  aws-assume-role:
    description: 'The ARN of an AWS IAM role to assume. Used to auth with AWS to upload results to S3.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Get current date
      shell: bash
      id: date
      run: echo "::set-output name=date::$(date +'%Y/%m/%d')"
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Run Gosec Security Scanner
      uses: securego/gosec@v2.14.0
      with:
        args: --exclude-generated=true --severity=medium --concurrency=1 --fmt json --out=gosec-results.json --stdout --verbose=text --no-fail ./...
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        audience: https://github.com/launchdarkly
        role-to-assume: ${{ inputs.aws-assume-role }}
        aws-region: us-east-1
    - name: Upload scan results to S3
      shell: bash
      run: |
        aws s3 cp ./gosec-results.json s3://launchdarkly-org-security-inventory/scan-results/gosec/${{ steps.date.outputs.date }}/$GITHUB_REPOSITORY.json
